#Octomap Parameters
/dsvplanner:
  ros__parameters:
    octo/tfFrame: map
    octo/robotFrame: sensor_at_scan
    octo/resolution: 0.18
    octo/probabilityHit: 0.65
    octo/probabilityMiss: 0.4
    octo/thresholdMin: 0.12
    octo/thresholdMax: 0.97
    octo/thresholdOccupancy: 0.7
    octo/filterSpeckles: true
    octo/maxFreeSpace: 0.0
    octo/minHeightFreeSpace: 0.0
    octo/sensorMaxRange: 15.0
    octo/visualizeMinZ: -25.0
    octo/visualizeMaxZ: 25.0
    octo/mapPublishFrequency: 1.0
    octo/treatUnknownAsOccupied: false
    octo/changeDetectionEnabled: false
    octo/velodyne_cloud_topic: /sensor_scan
