# Topics
world_frame_id                      : /map
graph_planner_command_topic         : /graph_planner_command
graph_planner_status_topic          : /graph_planner_status
pub_waypoint_topic                  : /way_point
pub_path_topic                      : /graph_planner_path
sub_graph_topic                     : /local_graph #/keypose_graph #
sub_odometry_topic                  : /state_estimation

# Constants
kLookAheadDist                      : 2.5 # the minimum distance between next goal vertex and current vertex
kWaypointToRobotDistance            : 3.0 # distance between waypoint and robot must larger than this value when going to location or home

